modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "justneeded"
version = "${version}"
displayName = "Just Needed"
authors = "JustDoom"
description = '''
This mod adds items, blocks, recipes that are "just needed" to be in minecraft!
'''
logoFile = "logo-forge.png"

[[dependencies.justneeded]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justneeded]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justneeded]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"