modLoader = "javafml"
loaderVersion = "[45,)"
#issueTrackerURL = ""
license = "GPLv3"

[[mods]]
modId = "justneeded"
version = "${version}"
displayName = "Just Needed"
authors = "JustDoom"
description = '''
This mod adds items, blocks, recipes that are just needed to be in minecraft!
'''
#logoFile = ""

[[dependencies.justneeded]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justneeded]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.justneeded]]
modId = "architectury"
mandatory = true
versionRange = "[8.1.79,)"
ordering = "AFTER"
side = "BOTH"